// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_9BWCe1URnsdqKAbvMO6E2auX1GgRUa4',
    appId: '1:932739100598:web:9d8e1dcc3a67bc74671b17',
    messagingSenderId: '932739100598',
    projectId: 'iseneca-91d65',
    authDomain: 'iseneca-91d65.firebaseapp.com',
    storageBucket: 'iseneca-91d65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjbQybVsf0zOeoj7RrAGTAW2osL2yX_mE',
    appId: '1:932739100598:android:8b9f0a351b1284e1671b17',
    messagingSenderId: '932739100598',
    projectId: 'iseneca-91d65',
    storageBucket: 'iseneca-91d65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIsyvsTXTf4CxByGNNpaRRAPqivAOLKig',
    appId: '1:932739100598:ios:e9a367f636de7de1671b17',
    messagingSenderId: '932739100598',
    projectId: 'iseneca-91d65',
    storageBucket: 'iseneca-91d65.firebasestorage.app',
    iosClientId: '932739100598-cnro5ce12v2j48aqtb4hoi6c56m4h4db.apps.googleusercontent.com',
    iosBundleId: 'com.example.iseneca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIsyvsTXTf4CxByGNNpaRRAPqivAOLKig',
    appId: '1:932739100598:ios:e9a367f636de7de1671b17',
    messagingSenderId: '932739100598',
    projectId: 'iseneca-91d65',
    storageBucket: 'iseneca-91d65.firebasestorage.app',
    iosClientId: '932739100598-cnro5ce12v2j48aqtb4hoi6c56m4h4db.apps.googleusercontent.com',
    iosBundleId: 'com.example.iseneca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_9BWCe1URnsdqKAbvMO6E2auX1GgRUa4',
    appId: '1:932739100598:web:04e626ebbdf6e5c4671b17',
    messagingSenderId: '932739100598',
    projectId: 'iseneca-91d65',
    authDomain: 'iseneca-91d65.firebaseapp.com',
    storageBucket: 'iseneca-91d65.firebasestorage.app',
  );
}
